{% set name = "argon2-cffi-bindings" %}
{% set version = "25.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: "b957f3e6ea4d55d820e40ff76f450952807013d361a65d7f28acc0acbf29229d"

build:
  number: 0
  script_env:
    - ARGON2_CFFI_USE_SSE2=0  # [not x86_64]
  script:
    - ln -sf $RANLIB $BUILD_PREFIX/bin/ranlib  # [unix]
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cffi >=1.0.1                           # [py < 314 and build_platform != target_platform]
    - cffi>=2.0.0b1                          # [py >= 314 and build_platform != target_platform]
    - {{ compiler("c") }}
    - {{ stdlib("c") }}

  host:
    - python
    - pip
    - cffi >=1.0.1                           # [py < 314]
    - cffi>=2.0.0b1                          # [py >= 314]
    - setuptools >=45
    - setuptools_scm >=6.2
    - wheel

  run:
    - python
    - cffi >=1.0.1                           # [py < 314]
    - cffi>=2.0.0b1                          # [py >= 314]

test:
  imports:
    - _argon2_cffi_bindings
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/hynek/argon2-cffi-bindings
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Low-level Python CFFI Bindings for Argon2
  description: |
    argon2-cffi-bindings provides low-level CFFI bindings to the Argon2
    password hashing algorithm including a vendored version of them.
  doc_url: https://github.com/hynek/argon2-cffi-bindings
  dev_url: https://github.com/hynek/argon2-cffi-bindings

extra:
  recipe-maintainers:
    - stuertz
